version: "3.9"
services:
  theharvester.svc.local:
    container_name: theHarvester
    volumes:
      - ./api-keys.yaml:/root/.theHarvester/api-keys.yaml
      - ./api-keys.yaml:/etc/theHarvester/api-keys.yaml
      - ./proxies.yaml:/etc/theHarvester/proxies.yaml
      - ./proxies.yaml:/root/.theHarvester/proxies.yaml
    build: .
    ports:
      - "8080:80"

networks:
  default:
    name: app_theHarvester_network
